### ISSUE TITLE
Unable to write to app

### ISSUE THREAD

**Issue by ghost** [talcs/tals_python_task_diary#2]
Hi @talcs - cool app. Nice layout, but I cannot write anything to the app. I cannot insert anything. How do I fix this? I am on a Mac. Thanks.

**Comment by talcs** [comment]
Simply right click on the white area of the table - a context menu will be shown and you'll be able to add a new task

**Comment by ghost** [comment]
Thanks for the response and your time. That is what I initially thought, but nothing happens when I right click. I am running Python 3.6.

I wonder if it has to do with certain imports? I have tkinter. Not sure what xml.etree.ElementTree is but the program runs with 0 errors. I have tried on both PyCharm and IDLE.

Any idea of what the issue may be?

**Comment by ghost** [comment]
Nvm, my mouse is dumb and the middle button is the right key. Makes no sense but whatever lol. Thanks!
